### ISSUE TITLE
need to source mappings.lua manually to work with mini.files

### ISSUE THREAD

**Issue by bassamsdata** [NvChad/tinyvim#2]
Hey, thank you for this well organized simple config.
I'm facing an issue with a plugin that I prefer over `nvim-tree` for files which is [mini.files](https://github.com/echasnovski/mini.files), the mapping seemed to not work properly.
added this to `plugins/init.lua`
```lua
  {
    "echasnovski/mini.files",
    lazy = false,
    config = function()
    require("mini.files").setup() 
    end,
  },
```

and this to the `mappings.lua`
```lua
map("n", "<leader>e", function()
  local MiniFiles = require "mini.files"
  if not MiniFiles.close() then
    MiniFiles.open()
  end
end, { desc = "File explorer" })
```
**the problem:** if I open nvim with any file, the mapping doesn't work, until I source the mappings file, like `:so lua/mappings.lua`
then it works. I open nvim with no arguments, it works until I open any file then it doesn't.
yest whenever I call `:lua MiniFiles.open()` it works. I find it that weird.

thank you again

**Comment by siduck** [comment]
@bassamsdata thats cuz space e is used by lspconfig already 

![image](https://github.com/NvChad/tinyvim/assets/59060246/66412bd5-32f0-4a53-b4d1-055c6b82c1a5)

**Comment by siduck** [comment]
and lspconfig is loaded just after opening a file ig so you cant use that

**Comment by siduck** [comment]
either map it to C-n or something else, or change <space>e to something else

also lazy=false is by default in tinyvim. Do lazy=true instead, cuz you're just loading the plugin by a mapping :D

**Comment by bassamsdata** [comment]
@siduck  oh thank you so much, I really didn't think to grep if there is a mapping to `<space>e` 🫣. my bad 

and again thank you for the tip for `lazy = true` :), I was trying trying to solve the issue.
