### ISSUE TITLE
Add a branch that uses blink.nvim instead nvim-cmp

### ISSUE THREAD

**Issue by voyeg3r** [NvChad/tinyvim#6]
Blink is a promissing faster and easiest config plugin

**Comment by siduck** [comment]
cmp has been around for years and is stable

**Comment by aqilc** [comment]
I would love a branch that uses blink.cmp, especially with it's maturity at this point and having integration with [xzbdmw/colorful-menu.nvim](https://github.com/xzbdmw/colorful-menu.nvim).

It's noticeably faster, less bloated and looks much, much nicer. I was thinking about using this distro until I saw it still used the old cmp.

**Comment by siduck** [comment]
this plugin uses blink now lol

**Comment by aqilc** [comment]
oh can you update the readme then

**Comment by siduck** [comment]
> oh can you update the readme then

done boss

**Comment by siduck** [comment]
> oh can you update the readme then

done dude!

**Comment by aqilc** [comment]
thank you!
